version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb
      - redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mongodb:
    image: mongo:5.0.5
    restart: always
    volumes:
      - ./.docker/mongodb:/data/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=analytics
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongodb
  
  redis:
    image: redis:6.2.6-alpine3.14
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis:/data/redis
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
